language: node_js
node_js:
- '10'
script: make load-menu ; make build
deploy:
  provider: pages
  repo: kulturebar/kulturebar.github.io
  target-branch: master
  email: putintsev@gmail.com
  fqdn: kulturebar.ru
  local-dir: ./dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
